# fly.toml app configuration file generated for bot-n on 2025-05-18T12:36:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bot-n"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https   = true
  # auto_start/auto_stop 周りは scale で管理するので削除

processes = ["app"]

# マシン数を明示的に固定
[scale]
  min     = 1
  max     = 1
  desired = 1

# 永続ボリュームは data1 のみ
[[mounts]]
source      = "data1"
destination = "/data"
